<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Tutorial</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <link rel="stylesheet" href="<?php echo APP_PATH.'/views/mystyle.css'?>">
</head>
<style> 


</style>
<body>
<div class="container">

    <?php echo $this->getContent(); ?>
</div>
</body>
<script>
   function myFunction() {
  /* Get the text field */
  var copyText = document.getElementById("myInput");

  /* Select the text field */
  copyText.select();
  copyText.setSelectionRange(0, 99999); /* For mobile devices */

   /* Copy the text inside the text field */
  navigator.clipboard.writeText(copyText.value);

  /* Alert the copied text */
  alert("Copied the text: " + copyText.value);
}
</script>
</html>